version: '3.1'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: news_compare_user
      POSTGRES_PASSWORD: news_compare_password
      POSTGRES_DB: news-compare-development
